# Generated by Django 3.0.2 on 2020-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=140, verbose_name='やること')),
                ('limit', models.IntegerField(blank=True, default=0, verbose_name='期限n（例、3以内）')),
            ],
        ),
    ]
