# Generated by Django 3.0.2 on 2020-08-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='existence',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
