# Generated by Django 3.0.2 on 2020-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_todo_existence'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
